name: PPO
channels:
  - defaults
  - conda-forge
dependencies:
  # Conda-managed dependencies (build strings removed)
  - python=3.10.16
  - bzip2
  - ca-certificates
  - libffi
  - openssl
  - pip
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib

  # Everything else was originally installed via pip, so we keep it that way:
  - pip:
      - absl-py==2.2.2
      - ale-py==0.10.2
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - etils==1.12.2
      - farama-notifications==0.0.4
      - filelock==3.18.0
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - glfw==2.8.0
      - grpcio==1.71.0
      - gymnasium==1.1.1
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - mujoco==3.3.1
      - networkx==3.4.2
      - numpy==2.2.4
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - protobuf==6.30.2
      - psutil==7.0.0
      - pygame==2.6.1
      - pygments==2.19.1
      - pyopengl==3.1.9
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rich==14.0.0
      - scipy==1.15.2
      - six==1.17.0
      - stable-baselines3==2.6.0
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - torch==
